user_manager/urls.py
from django.urls import path
from user_manager import views

urlpatterns = [
    path('', views.personal, name='personal'),
    path('change_password/', views.change_password, name='change_password')
]

yatracker/urls.py
from django.contrib import admin
from django.views.generic import RedirectView
from django.urls import path, include

urlpatterns = [
    path('', RedirectView.as_view(pattern_name='dashboard'), name='index'),
    path('dashboard/', include('project_manager.urls')),
    path('authentiation/', include('authentication.urls')),
    path('personal/', include('user_manager.urls')),
    path('admin/', admin.site.urls, name='admin'),
]

user_manager/models/roles.py
ROLES = (
        ('adm', 'Admin'),
        ('stu', 'Student'),
        ('ins', 'Instructor'),
        )

user_manager/models/user.py
from django.db import models
from django.core.exceptions import ValidationError
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager
from polymorphic.models import PolymorphicModel, PolymorphicManager

from yatracker.hashes import sha256

from .roles import ROLES


class UserManager(PolymorphicManager, BaseUserManager):
    use_in_migrations = True

    def create_user(self, email, password=None, **required_args):
        if not email or not password:
            raise ValueError("Users must have an email and password")

        user = self.model(email=email, **required_args)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, email, password, **required_args):
        user = self.create_user(email, password, **required_args)
        user.is_superuser = True
        user.is_staff = True
        user.save(using=self._db)
        return user


class User(PolymorphicModel, AbstractBaseUser):

    name = models.CharField(max_length=30)
    surname = models.CharField(max_length=30)
    email = models.EmailField(unique=True, max_length=256)
    password = models.CharField(max_length=128)
    user_type = models.CharField(max_length=3, choices=ROLES)

    # Methods and fields for enabling authentication on this model

    objects = UserManager()

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    is_superuser = models.BooleanField(default=False)
    is_staff = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)

    @classmethod
    def create(cls, **kwargs):
        user = cls(**kwargs)
        return user

    def has_perm(self, perm, obj=None):
        return self.is_superuser

    def has_module_perms(self, app_label):
        return self.is_superuser

    def set_password(self, raw_password):
        if self.email:
            self.password = sha256(self.email + raw_password)

    def check_password(self, raw_password):
        return self.password == sha256(self.email + raw_password)

    def get_full_name(self):
        return '{0} {1}'.format(self.name, self.surname)

    def get_short_name(self):
        return self.name

    def __str__(self):
        return self.get_full_name()


class Instructor(User):
    pass


class Student(User):
    pass


class Admin(User):
    pass

user_manager/forms.py
from django import forms


class PasswordChangeForm(forms.Form):

    old_password = forms.CharField(label="New Password", required=True, widget=forms.PasswordInput)
    new_password = forms.CharField(label="New Password", required=True, widget=forms.PasswordInput)
    password_repeat = forms.CharField(label="Repeat Password", required=True, widget=forms.PasswordInput)

    def clean(self):
        cleaned_data = super().clean()
        new_password = cleaned_data.get('new_password')
        password_repeat = cleaned_data.get('password_repeat')

        if new_password != password_repeat:
            self.add_error(
                'password_repeat',
                "Passwords don't match"
            )

        return cleaned_data

user_manager/views.py
from django.urls import reverse
from django.http import (
    HttpResponseRedirect,
)

from django.contrib.auth import update_session_auth_hash
from user_manager.forms import PasswordChangeForm
from django.shortcuts import render

from django.contrib.auth import get_user_model
User = get_user_model()


def require_authorized(function):
    def wrapper(request, *args, **kwargs):
        if not request.user.is_authenticated:
            return HttpResponseRedirect(reverse('login'))
        return function(request, *args, **kwargs)
    return wrapper


@require_authorized
def personal(request):
    user = User.objects.get(pk=request.user.id)
    return render(request, 'user_manager/account.html', {'user': user})


@require_authorized
def change_password(request):
    if request.method == 'POST':
        form = PasswordChangeForm(request.POST)
        if form.is_valid():
            user = User.objects.get(pk=request.user.id)
            old_pass = form.cleaned_data['old_password']
            new_pass = form.cleaned_data['new_password']
            if user.check_password(old_pass):
                user.set_password(new_pass)
                user.save()
                update_session_auth_hash(request, user)
                return personal(request)
    else:
        form = PasswordChangeForm()
    return render(request, 'user_manager/change_password.html', {'form': form})

user_manager/templates/user_manager/account.html
{% extends 'yatracker/base.html' %}
{% block content %}
    <div class="row">
        <div class="col-4">
            <div class="list-group" id="list-tab" role="tablist">
                <a class="list-group-item list-group-item-action active" id="list-home-list" data-toggle="list"
                   href="#list-home" role="tab" aria-controls="home">Profile info</a>
                <a class="list-group-item list-group-item-action" id="list-profile-list" data-toggle="list"
                   href="#list-profile" role="tab" aria-controls="profile">Projects</a>
                <a class="list-group-item list-group-item-action" id="list-messages-list" data-toggle="list"
                   href="#list-messages" role="tab" aria-controls="messages">Edit profile</a>
            </div>
        </div>
        <div class="col-8">
            <div class="tab-content" id="nav-tabContent">

                <div class="tab-pane fade show active" id="list-home" role="tabpanel" aria-labelledby="list-home-list">
                    <button type="button" class="list-group-item list-group-item-action">
                        {{ user.name }}
                    </button>
                    <button type="button" class="list-group-item list-group-item-action">{{ user.surname }}
                    </button>
                    <button type="button" class="list-group-item list-group-item-action">{{ user.email }}</button>
                    <button type="button"
                            class="list-group-item list-group-item-action">{{ user.get_user_type_display }}
                    </button>
                </div>
                <div class="tab-pane fade" id="list-profile" role="tabpanel" aria-labelledby="list-profile-list">
                    <ul class="list-group">
                        {% for project in user.projects.all %}
                            <li class="list-group-item">{{ project.title }}</li>
                        {% endfor %}
                    </ul>

                </div>
                <div class="tab-pane fade" id="list-messages" role="tabpanel" aria-labelledby="list-messages-list">
                    <a class="list-group-item list-group-item-action"
                        href="{% url 'change_password' %}" role="tab" aria-controls="messages">Change Password</a>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

user_manager/templates/user_manager/change_password.html
{% extends 'yatracker/base.html' %}
{% block scripts_and_links %}
<link href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.2/css/all.css" integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">
{% load static %}
<link rel="stylesheet" href="{% static 'css/registration.css' %}">
{% endblock %}
{% block title %}
Authorization
{% endblock %}
{% block content %}
<div class="row">
    <div class="col-md-4"></div>
    <div class="center-block col-md-4" id="change_password">
            <section id="inner-wrapper" class="login">
              <article>
                <form method="post">
                {% csrf_token %}
                  <div class="form-group">
                    <div class="input-group">
                      <span class="input-group-prepend"><div class="input-group-text"><i class="fa fa-key"> </i></div></span>
                      <input type="password" class="form-control" name="old_password" placeholder="Old password">
                    </div>
                  </div>
                  <div class="form-group">
                    <div class="input-group">
                      <span class="input-group-prepend"><div class="input-group-text"><i class="fa fa-key"> </i></div></span>
                      <input type="password" class="form-control" name="new_password" placeholder="New password">
                    </div>
                  </div>
                  <div class="form-group">
                    <div class="input-group">
                      <span class="input-group-prepend"><div class="input-group-text"><i class="fa fa-key"> </i></div></span>
                      <input type="password" class="form-control" name="password_repeat" placeholder="New password confirmation">
                    </div>
                  </div>
                    <button type="submit" class="btn btn-success btn-block">Change Password</button>
                </form>
              </article>
            </section>
    </div>
</div>
{% endblock %}